### ISSUE TITLE
CUDA not found/linked building pytorch inside a spack environment

### ISSUE THREAD

**Issue by flxmr** [LLNL/spack#29206]
### Steps to reproduce

I wanted to create an environment containing `py-torch@1.9.1+cuda`. Unfortunately it's not picking up CUDA, e.g. I get a `+cuda`-spec, but it's actually not properly linking CUDA! However it does, when building standalone with roughly the same spec (didn't lock every minor python dep but CUDA/cudnn/nccl)! The `spack-build-01-install-out.txt` says very weirdly it couldn't find CUDA (see below as "Error message"). This could be related to the fact that in the finished environment, the libcudart.so is also not found in the `LD_LIBRARY_PATH`.

I remember the last time I had this problem I just built the spec, then added this to the environment. However, due to added dependencies this is not feasible now.

### Error message

In the `spack-build-01-install-out.txt` I see that CUDA is not found when building within the environment:
```
  -- Could NOT find CUDA (missing: CUDA_CUDART_LIBRARY) (found version "10.2")
  CMake Warning at cmake/public/cuda.cmake:31 (message):
    Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
    or a Caffe2 dependent library, the next warning / error will give you more
    info.
  Call Stack (most recent call first):
    cmake/Dependencies.cmake:1155 (include)
    CMakeLists.txt:621 (include)
```

Correctly it is found, building standalone:
```
 -- Found CUDA: /home/private_software/spack_21Q4/opt/spack/linux-debian10-skylake_avx512/gcc-8.5.0/cuda-0.2.89-c53spuuc5e
7eb6ulbdsrurexw6sged6d (found version "10.2")
  -- Caffe2: CUDA detected: 10.2
  -- Caffe2: CUDA nvcc is: /home/private_software/spack_21Q4/opt/spack/linux-debian10-skylake_avx512/gcc-8.5.0/cuda-10.2.89-c53spuuc5e7eb6ulbdsrurexw6sged6d/bin/nvcc
  -- Caffe2: CUDA toolkit directory: /home/private_software/spack_21Q4/opt/spack/linux-debian10-skylake_avx512/gcc-8.5.0/cuda-10.2.89-c53spuuc5e7eb6ulbdsrurexw6sged6d
  -- Caffe2: Header version is: 10.2
  ```

### Information on your system

* **Spack:** 0.17.1
* **Python:** 3.7.3
* **Platform:** linux-debian10-cascadelake
* **Concretizer:** clingo
(head is at 9fef13ce95701449e467d1de5c5b1254f4cdfabc though)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by flxmr** [comment]
So this issue is annoying me a lot. It actually works, when building "outside", because for whatever reason, I can just build the exact spec outside and then it just gets picked up when doing a `spack install`. 

Weirdly I got a similar issue when building `py-torch-sparse`, where the installed and necessary pytorch is just not put in the `PYTHONPATH` for the build environment. "Outside" it is.

EDIT: ok, that problem was resolved by just activating and deactivating the environment.

**Comment by flxmr** [comment]
Also here: reverting before this: https://github.com/spack/spack/pull/27798 makes it work again.

**Comment by adamjstewart** [comment]
Hmm, #27798 should not affect CUDA detection. I would have to see the full build log and build environment to debug this.

**Comment by haampie** [comment]
Possibly #29217 solves this? If you depend on an environment view somehow, cuda libraries were not properly symlinked.
